source 'https://rubygems.org'

RAILS_VERSION = '3.2.8'
DM_VERSION    = '1.2.0'

gem 'rails',                RAILS_VERSION
gem 'mysql2'

case (ENV['ORM'] || '').downcase
when 'dm'
  # DataMapper
  gem 'dm-rails',           DM_VERSION
  gem 'dm-mysql-adapter',   DM_VERSION
  gem 'dm-validations',     DM_VERSION # needed for manual validations
  gem 'dm-timestamps',      DM_VERSION # needed for created_at and updated_at
  gem 'dm-aggregates',      DM_VERSION # needed for efficient count queries, else * will be selected and counted afterwards
when 'sq'
  gem 'sequel'  
end

# Get the latest sources from github
gem 'netzke-core',          :github => 'nomadcoder/netzke-core'
gem 'netzke-basepack',      :github => 'nomadcoder/netzke-basepack'
# gem 'netzke-core', path: "~/code/netzke/netzke-core"
# gem 'netzke-basepack', path: "~/code/netzke/netzke-basepack"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'pry'
  gem 'thin'
  gem 'capybara', '~>1'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  gem 'rspec-rails'
  gem 'spork-rails'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl_rails'
end

group :test do
  case (ENV['ORM'] || '').downcase
  when 'dm'
    # if we are using dm, we need the sqlite adapter
    gem 'dm-sqlite-adapter', DM_VERSION
  else
    # default case: use ar
    # nothing to do here
  end
  gem 'database_cleaner'
end
